version: "3.1"
services:
    www:
        build: .
        ports: 
            - "55124:80"
        volumes:
            - ./web:/var/www/html/:ro
        links:
            - db
        networks:
            - default
volumes:
    persistent: